### PR TITLE
Packagelock json bool resolved

### LINKED ISSUE #718: fossa analyze v.3 fails for npm repo when resolved is not URL in package-lock
`fossa analyze` used to work fine until v.2 with [an npm `package-lock.json` issue](https://stackoverflow.com/questions/62011779/npm-install-changes-resolved-from-a-url-to-false) which came up sometimes (exp when using `npm link`).

Apparently v.3 does not like it and this broke my build:

```
[ WARN] ----------
  An error occurred:

      Error parsing file /home/runner/work/spid-react-button/spid-react-button/package-lock.json:
          Error in $.dependencies['react-scripts'].resolved: parsing Text failed, expected String, but encountered Boolean

      Traceback:
        - Parsing JSON file '/home/runner/work/spid-react-button/spid-react-button/package-lock.json'
        - Parsing package-lock.json
        - Analyzing Npm Lockfile
        - Project Analysis

[ INFO] [ 0 Waiting / 2 Running / 34 Completed ]
Error:  ----------
  An error occurred:

      No analysis targets found in directory.

      Make sure your project is supported. See the user guide for details:
          fossas/fossa-cli@v3.0.4/docs/README.md


      Traceback:
        - fossa-analyze
```
( [full log here](https://github.com/dej611/spid-react-button/runs/4309530200?check_suite_focus=true) )

I could not reproduce it locally because of #717 it takes forever to run the whole check on my machine (I stopped the process after 30 minutes and it was still half way... ).

### PR DESCRIPTION
**Pull request by csasarak**
# Overview

This fixes a parser error when a `package-lock.json` dependency's `resolved` key is a boolean rather than a string.

## Acceptance criteria

The parser for `package-lock.json` dependencies should ignore a boolean `resolved` key.

## Testing plan

I added unit tests for the dependency parser. I also manually ran `fossa analyze` against the repo referenced in #718 and verified that it now parses successfully.

To reproduce you can run the master branch's `fossa analyze` against the repo in the above issue.

## References

Closes fossas/team-analysis#849
Closes #718 

## Checklist

- [x] I added tests for this PR's change (or confirmed tests are not viable).
- [x] If this PR introduced a user-visible change, I added documentation into `docs/`.
- [x] I updated `Changelog.md` if this change is externally facing. If this PR did not mark a release, I added my changes into an `# Unreleased` section at the top.
- [x] I updated `*schema.json` if I have made changes for `.fossa.yml`, `fossa-deps.{json, yaml, yml}`. You may also need to update these if you have added/removed new dependency (e.g. pip) or analysis target type (e.g. poetry).
- [x] I linked this PR to any referenced GitHub issues, if they exist.

### CODE REVIEW

File: test/Node/NpmLockSpec.hs [hunk 1]
```diff
@@ -170,3 +193,24 @@ spec = do
...
         ]
         graph
+  describe "parsing package-json.lock" $ do
+    currentDir <- runIO getCurrentDir
+    let testDir = currentDir </> $(mkRelDir "test/Node/testdata")
+
+    it' "Should ignore \"resolved\": <bool> in package-lock.json" $ do
+      let packageLock = testDir </> $(mkRelFile "boolean-resolved-package-lock.json")
+      NpmPackageJson{packageDependencies = packageDependencies} <- readContentsJson packageLock
+      let foo = Map.lookup "foo" packageDependencies >>= unNpmResolved . depResolved
```
Comment (scruffystuffs) [inline test/Node/NpmLockSpec.hs:203]: [nit]: This is one of the cases where flipped operators make things more readable.  Currently, the code has to be read as:

```haskell
firstOp >>= thirdOp . secondOp
```
However, we can use the right-to-left style of the `.` operator and justify using `=<<` (which is normally discouraged in the style guide), because then the ordering flows neatly from one side of the expression to the other.
```suggestion
      let foo = unNpmResolved . depResolved =<< Map.lookup "foo" packageDependencies
```

If you choose to add this, probably best to change the other tests as well.

**Review by scruffystuffs — APPROVED** [review]
LGTM, one comment about test readability

File: test/Node/NpmLockSpec.hs (hunk 1 above)
Comment (csasarak) [reply test/Node/NpmLockSpec.hs]: Thanks, I have incorporated this suggestion.

Comment (scruffystuffs) [reply test/Node/NpmLockSpec.hs]: I've added this to the style guide in #776
