### PR TITLE
fix(install): avoid hitting rate limit on install script

### LINKED ISSUE #180: Avoid hitting rate limit on installation script
Our installation script currently queries the GitHub Releases API to discover the latest release for download. When it is run many times in rapid succession (e.g. in parallel across many CI machines), this hits the rate limit and causes the installation script to fail.

Several options:

1. Generate a new installation script for every release, hardcoding the release download link. Downloading releases or from `raw.githubusercontent.com` is not rate limited.
2. Add a user option to specify a `GITHUB_TOKEN` to the request. Authenticated requests are not rate limited.
3. Create our own `GITHUB_TOKEN` with no permissions, and use this to authenticate the request.

Personally, option 1 seems like the best choice. It adds the most complexity, but provides the best user experience and seems easily maintainable.

See also:

- [Installer code that queries the Releases API](https://github.com/fossas/fossa-cli/blob/master/install.sh#L108)
- [Releases API documentation](https://developer.github.com/v3/repos/releases/)
- [Rate limit documentation](https://developer.github.com/v3/#rate-limiting)

### PR DESCRIPTION
**Pull request by emilyzhang**
Fixes #180 by generating a new install.sh (from install_tpl.sh) for each new release. Does not (yet) fix the issue for Windows users, however.

### CODE REVIEW

File: Makefile [hunk 1]
```diff
@@ -79,4 +79,7 @@ clean:
 
 .PHONY: release
 release:
+	SHELL:=/bin/bash
```
Comment (ilikebits) [inline Makefile]: What does this line do?

File: install_tpl.sh [hunk 2]
```diff
@@ -10,6 +10,7 @@
 
 TMP_DIR="/tmp/install-fossa-cli"
 
+
```
Comment (ilikebits) [inline install_tpl.sh]: [nit] Extra whitespace.

Comment (emilyzhang) [reply install_tpl.sh]: It's intentional, because a line will be added at line 12 when each new file is generated.

File: Makefile (hunk 1 above)
Comment (emilyzhang) [reply Makefile]: Sets the shell to be bash for the release target, and only the release target. Might not be a good idea for portability reasons (?) but I wanted to make sure that I could use sed in the Makefile. It might be unneeded.

File: install_tpl.sh (hunk 2 above)
Comment (ilikebits) [reply install_tpl.sh]: You should add a comment indicating this. Another option might be e.g. a "REPLACE ME" comment that you use as a replacement target for `sed`.

File: Makefile (hunk 1 above)
Comment (ilikebits) [reply Makefile]: This isn't necessary. Our release process always runs in the the `quay.io/fossas/fossa-cli` Docker container, which uses `bash`.

File: Makefile [hunk 3]
```diff
@@ -79,4 +79,7 @@ clean:
 
 .PHONY: release
 release:
-	GOVERSION=$$(go version) goreleaser --rm-dist
+	GOVERSION=$(go version) goreleaser --rm-dist
```
Comment (ilikebits) [inline Makefile]: This should be `$$(go version)` instead of `$(go version)`. Note the extra `$`.

File: install_tpl.sh [hunk 4]
```diff
@@ -105,10 +105,10 @@ function install {
   cd $TMP_DIR || fail "changing directory to $TMP_DIR failed"
 
   # Download and validate release
-  bash -c "$GET $GH_API/repos/$USER/$REPO/releases/latest" > latest || fail "downloading latest release metadata failed"
-  RELEASE=$(grep tag_name latest | cut -d'"' -f4)
-  VERSION=${RELEASE#v} # remove prefix "v"
-
+  # Do not remove the following two lines. They are used to generate
```
Comment (ilikebits) [inline install_tpl.sh]: I would prefer these in ALLCAPS.

**Comment by ilikebits** [comment]
PR builds are failing due to #115. This LGTM; merging.
